services:
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - keycloack_network
  keycloack:
    image: keycloak/keycloak:26.0
    command: 
      - start-dev
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/keykloak/imports/realm-exports.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    environment:
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_PORT: "8080"
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: false
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOACK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOACK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./keykloak/realm-exports.json:/opt/keykloak/imports/realm-exports.json
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloack_network

volumes:
  postgres_data:
    driver: local
networks:
  keycloack_network:
    driver: bridge